import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import DashboardLayout from "../../components/dashboard/DashboardLayout";
import { getMyBookings, getBookingSession } from "../../api/bookings";
import { getMyTeacherProfile } from "../../api/teachers";

const TEACHER_NAV = [
  { label: "Teaching", items: [{ path: "/dashboard/teacher", label: "Dashboard" }, { path: "/dashboard/teacher/calendar", label: "Calendar" }] },
  { label: "Profile", items: [{ path: "/dashboard/teacher/profile", label: "Teacher Profile" }] },
];
const formatDate = (v) => new Date(v).toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric", year: "numeric" });
const formatTime = (v) => new Date(v).toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" });
const getEndTime = (start, minutes) => { const d = new Date(start); d.setMinutes(d.getMinutes() + minutes); return formatTime(d); };
const isUpcoming = (b) => new Date(b.scheduled_at) > new Date() && b.status === "confirmed";
const isSameDay = (v) => { const d = new Date(v), t = new Date(); return d.getFullYear() === t.getFullYear() && d.getMonth() === t.getMonth() && d.getDate() === t.getDate(); };

export default function TeacherDashboard() {
  const navigate = useNavigate();
  const [bookings, setBookings] = useState([]), [profile, setProfile] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState(""), [profileError, setProfileError] = useState("");
  const [joiningBookingId, setJoiningBookingId] = useState(null);
  const load = async () => { setLoading(true); setError(""); const [b, p] = await Promise.allSettled([getMyBookings(), getMyTeacherProfile()]); if (b.status === "fulfilled") setBookings(Array.isArray(b.value) ? b.value : []); else setError(b.reason?.response?.data?.detail || "Unable to load your classes."); if (p.status === "fulfilled") setProfile(p.value); else setProfileError(p.reason?.response?.data?.detail || "Unable to load your profile."); setLoading(false); };
  useEffect(() => { load(); }, []);
  const upcoming = useMemo(() => bookings.filter(isUpcoming).sort((a, b) => new Date(a.scheduled_at) - new Date(b.scheduled_at)), [bookings]);
  const today = useMemo(() => bookings.filter((b) => isSameDay(b.scheduled_at)).sort((a, b) => new Date(a.scheduled_at) - new Date(b.scheduled_at)), [bookings]);
  const completed = useMemo(() => bookings.filter((b) => b.status === "completed"), [bookings]);
  const join = async (booking) => { if (joiningBookingId) return; setJoiningBookingId(booking.id); setError(""); try { const session = await getBookingSession(booking.id); navigate(`/classroom/${session.id}`); } catch (e) { setError(e.response?.data?.detail || "This classroom is not ready yet."); } finally { setJoiningBookingId(null); } };

  if (loading) return <DashboardLayout navItems={TEACHER_NAV}><div className="flex min-h-full items-center justify-center p-8"><p className="text-sm text-chalk-muted">Loading your teacher dashboard…</p></div></DashboardLayout>;
  return <DashboardLayout navItems={TEACHER_NAV}><div className="relative flex min-h-full flex-col"><div className="border-b border-chalk-faint px-8 py-5.5"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="text-sm text-chalk-muted">Teacher Dashboard</p><h1 className="mt-1 text-3xl font-semibold">Welcome back{profile?.full_name ? `, ${profile.full_name}` : ""}</h1><p className="mt-2 text-sm text-chalk-muted">Manage your classes, schedule, and teaching profile.</p></div><Link to="/dashboard/teacher/profile" className="inline-flex items-center justify-center rounded-xl bg-brand-red px-5 py-3 text-sm font-semibold">Edit Profile</Link></div></div><div className="flex-1 overflow-auto px-8 py-7">{joiningBookingId && <div className="fixed inset-0 z-50 grid place-items-center bg-black/60 backdrop-blur-sm"><div className="rounded-2xl border border-chalk-faint bg-panel px-8 py-7 text-center shadow-2xl"><div className="mx-auto mb-4 h-8 w-8 animate-spin rounded-full border-2 border-chalk-muted border-t-brand-gold"/><h3 className="text-base font-semibold">Opening classroom…</h3><p className="mt-1 text-sm text-chalk-muted">Connecting you securely. Please wait.</p></div></div>}{profileError && <div className="mb-4 rounded-xl border border-brand-red/30 bg-brand-red/10 px-4 py-3 text-sm text-brand-red">{profileError}</div>}{error && <div className="mb-6 rounded-xl border border-brand-red/30 bg-brand-red/10 px-4 py-3 text-sm text-brand-red">{error}<button onClick={load} className="ml-3 underline">Retry</button></div>}<div className="mb-8 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Total Classes" value={bookings.length}/><Stat label="Upcoming" value={upcoming.length}/><Stat label="Today" value={today.length}/><Stat label="Completed" value={completed.length}/></div><section className="mb-8"><h2 className="text-xl font-semibold">Today's Classes</h2><p className="mt-1 text-sm text-chalk-muted">Classes scheduled for today.</p><div className="mt-4">{today.length ? <div className="space-y-3">{today.map((b) => <BookingCard key={b.id} booking={b} onJoin={join} joining={joiningBookingId === b.id}/>)}</div> : <Empty text="You have no classes scheduled for today."/>}</div></section><section><h2 className="text-xl font-semibold">Upcoming Classes</h2><p className="mt-1 text-sm text-chalk-muted">Your next scheduled classes.</p><div className="mt-4">{upcoming.length ? <div className="space-y-3">{upcoming.slice(0, 10).map((b) => <BookingCard key={b.id} booking={b} onJoin={join} joining={joiningBookingId === b.id}/>)}</div> : <Empty text="No upcoming classes."/>}</div></section></div></div></DashboardLayout>;
}
function Stat({ label, value }) { return <div className="rounded-2xl border border-chalk-faint bg-panel p-5"><p className="text-sm text-chalk-muted">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>; }
function Empty({ text }) { return <div className="rounded-2xl border border-chalk-faint bg-panel p-8"><p className="text-sm text-chalk-muted">{text}</p></div>; }
function BookingCard({ booking, onJoin, joining }) { return <div className="rounded-2xl border border-chalk-faint bg-panel p-5"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><h3 className="font-semibold">{booking.subject_name}</h3><p className="mt-1 text-sm text-chalk-muted">Student: {booking.student_name}</p><p className="mt-1 text-sm text-chalk-muted">{formatDate(booking.scheduled_at)} • {formatTime(booking.scheduled_at)} – {getEndTime(booking.scheduled_at, booking.duration_minutes)}</p></div><div className="flex items-center gap-3"><span className="rounded-full bg-green-500/10 px-3 py-1.5 text-xs font-medium text-green-400">{booking.status}</span>{booking.teacher_assignment_status === "assigned" && <span className="rounded-full bg-green-500/10 px-3 py-1.5 text-xs font-medium text-green-400">Assigned</span>}<button disabled={!!joining} onClick={() => onJoin(booking)} className="rounded-lg bg-brand-red px-4 py-2 text-xs font-semibold disabled:opacity-60">{joining ? "Opening…" : "Join classroom"}</button></div></div></div>; }
