import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import TeacherDashboardLayout from "../../components/TeacherDashboardLayout";
import { getMyBookings, getBookingSession } from "../../api/bookings";
import { getMyTeacherProfile } from "../../api/teachers";

const formatDate = (v) => new Date(v).toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric", year: "numeric" });
const formatTime = (v) => new Date(v).toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" });
const getEndTime = (start, minutes) => { const d = new Date(start); d.setMinutes(d.getMinutes() + minutes); return formatTime(d); };
const isUpcoming = (b) => new Date(b.scheduled_at) > new Date() && b.status === "confirmed";
const isSameDay = (v) => { const d = new Date(v), t = new Date(); return d.getFullYear() === t.getFullYear() && d.getMonth() === t.getMonth() && d.getDate() === t.getDate(); };

export default function TeacherDashboard() {
  const navigate = useNavigate();
  const [bookings, setBookings] = useState([]), [profile, setProfile] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState(""), [profileError, setProfileError] = useState("");
  const [joiningBookingId, setJoiningBookingId] = useState(null);
  const load = async () => { setLoading(true); setError(""); const [b, p] = await Promise.allSettled([getMyBookings(), getMyTeacherProfile()]); if (b.status === "fulfilled") setBookings(Array.isArray(b.value) ? b.value : []); else setError(b.reason?.response?.data?.detail || "Unable to load your classes."); if (p.status === "fulfilled") setProfile(p.value); else setProfileError(p.reason?.response?.data?.detail || "Unable to load your profile."); setLoading(false); };
  useEffect(() => { load(); }, []);
  const upcoming = useMemo(() => bookings.filter(isUpcoming).sort((a, b) => new Date(a.scheduled_at) - new Date(b.scheduled_at)), [bookings]);
  const today = useMemo(() => bookings.filter((b) => isSameDay(b.scheduled_at)).sort((a, b) => new Date(a.scheduled_at) - new Date(b.scheduled_at)), [bookings]);
  const completed = useMemo(() => bookings.filter((b) => b.status === "completed"), [bookings]);
  const join = async (booking) => { if (joiningBookingId) return; setJoiningBookingId(booking.id); setError(""); try { const session = await getBookingSession(booking.id); navigate(`/classroom/${session.id}`); } catch (e) { setError(e.response?.data?.detail || "This classroom is not ready yet."); } finally { setJoiningBookingId(null); } };
  if (loading) return <TeacherDashboardLayout><div className="grid min-h-screen place-items-center p-6"><div className="text-center"><div className="mx-auto mb-3 h-8 w-8 animate-spin rounded-full border-2 border-chalk-faint border-t-brand-gold"/><p className="text-sm text-chalk-muted">Loading your teacher dashboard…</p></div></div></TeacherDashboardLayout>;
  return <TeacherDashboardLayout><div className="flex min-h-screen flex-col"><header className="border-b border-chalk-faint bg-panel/50 px-5 py-6 sm:px-7 lg:px-9"><div className="mx-auto flex w-full max-w-[1500px] flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-brand-gold">Teacher Dashboard</p><h1 className="mt-2 text-2xl font-semibold tracking-tight sm:text-3xl">Welcome back{profile?.full_name ? `, ${profile.full_name}` : ""}</h1><p className="mt-2 max-w-2xl text-sm text-chalk-muted">Manage your classes, schedule, and teaching profile from one place.</p></div><Link to="/dashboard/teacher/profile" className="inline-flex w-fit items-center justify-center gap-2 rounded-xl bg-brand-red px-5 py-3 text-sm font-semibold shadow-lg shadow-brand-red/10 transition hover:brightness-110">Edit Profile <span aria-hidden="true">→</span></Link></div></header>
  <div className="flex-1 overflow-auto px-5 py-6 sm:px-7 lg:px-9 lg:py-8"><div className="mx-auto w-full max-w-[1500px]">{joiningBookingId && <div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4 backdrop-blur-sm"><div className="w-full max-w-sm rounded-2xl border border-chalk-faint bg-panel p-7 text-center shadow-2xl"><div className="mx-auto mb-4 h-8 w-8 animate-spin rounded-full border-2 border-chalk-muted border-t-brand-gold"/><h3 className="text-base font-semibold">Opening classroom…</h3><p className="mt-1 text-sm text-chalk-muted">Connecting you securely. Please wait.</p></div></div>}
  {profileError && <div className="mb-5 rounded-xl border border-brand-gold/30 bg-brand-gold/10 px-4 py-3 text-sm text-chalk">{profileError}</div>}{error && <div className="mb-5 flex flex-col gap-2 rounded-xl border border-brand-red/30 bg-brand-red/10 px-4 py-3 text-sm text-brand-red sm:flex-row sm:items-center sm:justify-between"><span>{error}</span><button onClick={load} className="font-semibold underline underline-offset-2">Retry</button></div>}
  <div className="mb-8 grid grid-cols-2 gap-3 sm:grid-cols-4 sm:gap-4"><Stat label="Total Classes" value={bookings.length}/><Stat label="Upcoming" value={upcoming.length}/><Stat label="Today" value={today.length}/><Stat label="Completed" value={completed.length}/></div>
  <section className="mb-8"><SectionTitle title="Today's Classes" subtitle="Classes scheduled for today."/><div className="mt-4">{today.length ? <div className="space-y-3">{today.map((b) => <BookingCard key={b.id} booking={b} onJoin={join} joining={joiningBookingId === b.id}/>)}</div> : <Empty text="You have no classes scheduled for today."/>}</div></section>
  <section><SectionTitle title="Upcoming Classes" subtitle="Your next scheduled classes."/><div className="mt-4">{upcoming.length ? <div className="space-y-3">{upcoming.slice(0, 10).map((b) => <BookingCard key={b.id} booking={b} onJoin={join} joining={joiningBookingId === b.id}/>)}</div> : <Empty text="No upcoming classes."/>}</div></section></div></div></div></TeacherDashboardLayout>;
}
function SectionTitle({ title, subtitle }) { return <div><h2 className="text-xl font-semibold tracking-tight">{title}</h2><p className="mt-1 text-sm text-chalk-muted">{subtitle}</p></div>; }
function Stat({ label, value }) { return <div className="rounded-2xl border border-chalk-faint bg-panel p-4 shadow-sm transition hover:border-chalk-muted/30 sm:p-5"><p className="text-xs font-medium uppercase tracking-wide text-chalk-muted">{label}</p><p className="mt-2 text-2xl font-semibold sm:text-3xl">{value}</p></div>; }
function Empty({ text }) { return <div className="rounded-2xl border border-dashed border-chalk-faint bg-panel/60 p-7 sm:p-8"><p className="text-sm text-chalk-muted">{text}</p></div>; }
function BookingCard({ booking, onJoin, joining }) { return <article className="rounded-2xl border border-chalk-faint bg-panel p-4 shadow-sm transition hover:-translate-y-0.5 hover:border-chalk-muted/30 hover:shadow-lg sm:p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate font-semibold">{booking.subject_name}</h3>{booking.teacher_assignment_status === "assigned" && <span className="rounded-full bg-green-500/10 px-2.5 py-1 text-[11px] font-medium text-green-400">Assigned</span>}</div><p className="mt-2 text-sm text-chalk-muted">Student: {booking.student_name}</p><p className="mt-1 text-sm text-chalk-muted">{formatDate(booking.scheduled_at)} · {formatTime(booking.scheduled_at)} – {getEndTime(booking.scheduled_at, booking.duration_minutes)}</p></div><div className="flex w-full flex-wrap items-center gap-2 lg:w-auto lg:justify-end"><span className="rounded-full bg-green-500/10 px-3 py-1.5 text-xs font-medium capitalize text-green-400">{booking.status}</span><button disabled={!!joining} onClick={() => onJoin(booking)} className="min-w-32 rounded-lg bg-brand-red px-4 py-2.5 text-xs font-semibold transition hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-60">{joining ? "Opening…" : "Join classroom"}</button></div></div></article>; }
