import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import DashboardLayout from "../../../components/dashboard/DashboardLayout";
import { getMyTeacherProfile, getMyPendingTeacherProfileChange } from "../../../api/teachers";
import { getSubjects } from "../../../api/subjects";

const NAV=[{label:"Teaching",items:[{path:"/dashboard/teacher",label:"Dashboard"},{path:"/dashboard/teacher/calendar",label:"Calendar"}]},{label:"Profile",items:[{path:"/dashboard/teacher/profile",label:"Teacher Profile"}]}];
export default function TeacherProfileView(){const[p,setP]=useState(null),[subjects,setSubjects]=useState([]),[pending,setPending]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");useEffect(()=>{Promise.all([getMyTeacherProfile(),getSubjects(),getMyPendingTeacherProfileChange()]).then(([profile,allSubjects,request])=>{setP(profile);setSubjects(allSubjects);setPending(request)}).catch(e=>setError(e.response?.data?.detail||"Unable to load your profile.")).finally(()=>setLoading(false))},[]);const names=(p?.subject_ids||[]).map(id=>subjects.find(s=>s.id===id)?.name).filter(Boolean);return <DashboardLayout navItems={NAV}><div className="border-b border-chalk-faint px-8 py-5.5"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="text-sm text-chalk-muted">Profile</p><h1 className="mt-1 text-2xl font-semibold">Teacher Profile</h1><p className="mt-1 text-sm text-chalk-muted">Your approved professional information.</p></div><Link to="/dashboard/teacher/profile/edit" className="rounded-xl bg-brand-red px-5 py-3 text-sm font-semibold">Edit Profile</Link></div></div><div className="flex-1 overflow-auto px-8 py-7">{error&&<div className="mb-6 rounded-xl border border-brand-red/30 bg-brand-red/10 px-4 py-3 text-sm text-brand-red">{error}</div>}{loading?<p className="text-sm text-chalk-muted">Loading profile…</p>:p&&<div className="max-w-4xl space-y-5">{pending&&<div className="rounded-xl border border-brand-gold/30 bg-brand-gold/10 px-5 py-4 text-sm"><strong>Profile change pending review.</strong><p className="mt-1 text-chalk-muted">Your requested changes are waiting for admin approval. Your current approved profile remains active until approval.</p></div>}<section className="rounded-2xl border border-chalk-faint bg-panel p-6"><div className="grid gap-6 sm:grid-cols-2"><Info label="Name" value={p.full_name||"—"}/><Info label="Email" value={p.email||"—"}/><Info label="Phone" value={p.phone||"—"}/><Info label="Verification" value={p.is_verified?"Verified":"Pending verification"}/><Info label="Experience" value={p.years_experience!=null?`${p.years_experience} years`:"—"}/><Info label="Hourly rate" value={p.hourly_rate!=null?String(p.hourly_rate):"—"}/></div></section><section className="rounded-2xl border border-chalk-faint bg-panel p-6"><Info label="About" value={p.bio||"Not provided"}/><div className="mt-6"><Info label="Qualifications" value={p.qualifications||"Not provided"}/></div><div className="mt-6"><p className="text-xs uppercase tracking-wide text-chalk-muted">Subjects</p><div className="mt-3 flex flex-wrap gap-2">{names.length?names.map(n=><span key={n} className="rounded-full border border-chalk-faint px-3 py-1.5 text-sm">{n}</span>):<span className="text-sm text-chalk-muted">No subjects listed</span>}</div></div></section></div>}</div></DashboardLayout>}
function Info({label,value}){return <div><p className="text-xs uppercase tracking-wide text-chalk-muted">{label}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{value}</p></div>}
